spring.application.name=blogging-platform-api
spring.datasource.url=jdbc:postgresql://localhost:5432/blog_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.key.secret=0ade216e497a47165635699d02aaa031897206d0d1168282c2f0c8d0e1b3fbbc
security.jwt.user.generator=AUTH0JWT-ADMIN